# Generated by Django 6.0 on 2025-12-11 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('genre', models.CharField(blank=True, max_length=15)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_app.author')),
            ],
        ),
    ]
